project:
  type: website
  render:
    - "*.qmd"

website:
  title: "NFIDD EMBL-EBI"
  site-url: https://nfidd.github.io/EMBL-EBI/
  repo-url: https://github.com/nfidd/EMBL-EBI
  repo-actions: [source, issue]
  description: "Nowcasting and forecasting infectious disease dynamics - EMBL-EBI"
  body-footer: '<script data-goatcounter="https://nfidd.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>'
  open-graph: true
  favicon: nfidd-favicon.png
  navbar:
    left:
      - getting-started.qmd
      - sidebar:sessions
      - sidebar:reference
      - authors.qmd
    right:
      - icon: github
        href: https://github.com/nfidd/EMBL-EBI
  sidebar:
    - id: reference
      title: "Reference"
      style: "docked"
      contents: "reference/*.qmd"
    - id: sessions
      title: "Sessions"
      style: "docked"
      contents: "sessions/*.qmd"

execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    toc: true
