---
title: "Session timetable"
order: 1
comments: false
---

# EMBL-EBI Course: Rt estimation and nowcasting

**Tuesday - Half day**

Tuesday: 09.00-09.15

-   Course introduction and overview (15 mins)

## Session 1: $R_t$ estimation and the renewal equation

Tuesday: 09.15-10.00

-   [Introduction](../sessions/slides/introduction-to-reproduction-number): the time-varying reproduction number (10 mins)
-   [Practice](../sessions/R-estimation-and-the-renewal-equation): using the renewal equation to estimate R (30 mins)
-   Wrap up (5 mins)

## Session 2: Nowcasting concepts

Tuesday: 10.00-10.30

-   [Introduction](../sessions/slides/introduction-to-nowcasting): nowcasting as a right-truncation problem (10 mins)
-   [Practice](../sessions/nowcasting): simulating and basic nowcasting (20 mins)

## Session 3: Nowcasting with an unknown reporting delay

Tuesday: 11.00-12.00

-   [Introduction](../sessions/slides/introduction-to-joint-estimation-of-nowcasting-and-reporting-delays): joint estimation of delays and nowcasts (10 mins)
-   [Practice](../sessions/joint-nowcasting):
    -   joint estimation of delays and nowcasts (20 mins)
    -   joint estimation of delays, nowcasts and reproduction numbers (20 mins)
-   Wrap up (10 mins)

Tuesday: 12.00-12.30

-   Course wrap-up and discussion (30 mins)
